[[protocols]]
name = "rs500"
protocol = "jvc"
[protocols.scancodes]

# Note: Codes beginning with 63 are code-b while
# codes beginning with 73 are code-a

0x632e = "KEY_MENU"

#HDMI 1
0x6370 = "KEY_1"

#HDMI 2
0x6371 = "KEY_2"

#FILM-B
0x6369 = "KEY_3"

#CINEMA-B
0x6368 = "KEY_4"

#NATURAL-B
0x636A = "KEY_5"

#On
0x6305 = "KEY_F1"

#Off
0x6306 = "KEY_F2"
